/*
 * HSevenSegement_Config.h
 *
 *  Created on: Jan 26, 2023
 *      Author: 20109
 */

#ifndef HAL_SEVEN_SEGMENT_HSEVENSEGEMENT_CONFIG_H_
#define HAL_SEVEN_SEGMENT_HSEVENSEGEMENT_CONFIG_H_

enum SevenSegmentConnection{COMMON_ANODE,COMMON_CATHODE};

#define SEVENSEGMENT1_PORT PORT_A
#define SEVENSEGMENT1_CONNECTION COMMON_CATHODE

#define SEVENSEGMENT2_PORT PORT_B
#define SEVENSEGMENT2_CONNECTION COMMON_CATHODE

#endif /* HAL_SEVEN_SEGMENT_HSEVENSEGEMENT_CONFIG_H_ */
